### ISSUE TITLE
This doesn't work yet.

### ISSUE THREAD

**Issue by jbenet** [ipfs/ipfs-hubot#1]
heads up. will implement stuff here: https://github.com/ipfs/ipfs-hubot

**Comment by harlantwood** [comment]
What is the intended functionality?

**Comment by jbenet** [comment]
Being able to say -- on any hubot system, including github:

> jbenet: @ipfsbot pin /ipfs/QmdUsL8yWL8nKGh43i1ExWmwX9ALbxBgXd7zkRaHVxciDy

and have hubot reply:

> ipfsbot: @jbenet: pinned /ipfs/QmdUsL8yWL8nKGh43i1ExWmwX9ALbxBgXd7zkRaHVxciDy

basically, pinbot but on hubot, in particular over github

**Comment by harlantwood** [comment]
Sure, that's what I thought.

This gave me an idea for an IPFS dataviz bot...

> @bot viz QmdUsL8yWL8nKGh43i1ExWmwX9ALbxBgXd7zkRaHVxciDy

Could give you a link to a default viz, which would load inline in lots of
hubut contexts...

And of course you could specify a viz type once we have a few working...
Command line for viz : )

Jack and I are working on viz stuff today and might do a bit of hubot
wiring too.... Juan do you like the idea of viz commands in _this_ hubot?
Otherwise we could make a dedicated viz instance.

**Comment by harlantwood** [comment]
Also @jbenet what do you mean by "in particular over github"?

**Comment by jbenet** [comment]
Viz sounds great here!

Over github means that it's a GitHub bot, responds to commands on GitHub to authed accounts

—

**Comment by jbenet** [comment]
this works now
